apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:5.7.2-php8.0-fpm-alpine
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: 'mysqlpwd'
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
    - name: mysql
      image: mysql:8.0.25
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'mysqlpwd'
